_BASE_: "Base-CRCNN-COCO.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p67_resnest_fpn_backbone"
  PIXEL_MEAN: [123.68, 116.779, 103.939]
  PIXEL_STD: [58.393, 57.12, 57.375]
  RESNETS:
    DEPTH: 200
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
  META_ARCHITECTURE: "UnifiedRCNN"
  ROI_HEADS:
    NUM_CLASSES: 722
    NAME: "UnifiedCascadeROIHeads"
  ROI_BOX_HEAD:
    USE_SIGMOID_CE: True
    # USE_EQL_LOSS: True
    HIERARCHY_IGNORE: True
    HIERARCHY_POS_PARENTS: True
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
INPUT:
  FORMAT: "RGB"
DATASETS:
  TRAIN: ("objects365_train","coco_2017_train","oid_train","mapillary_960_train")
  TEST: ("coco_2017_val", "objects365_val", "oid_val_v2_expanded","mapillary_val")
DATALOADER:                                                                                                                                                                                                                                                                                                                                                                 
  SAMPLER_TRAIN: "MultiDatasetSampler"
  NUM_WORKERS: 1
MULTI_DATASET:
  ENABLED: True
  DATASETS: ['objects365', 'coco', 'oid', 'mapillary']
  NUM_CLASSES: [365, 80, 500, 37]
  DATA_RATIO: [1, 1, 1, 1]
  USE_CAS: [True, False, True, False]
  UNIFIED_LABEL_FILE: 'experts/obj_detection/datasets/label_spaces/learned_mAP+M.json'
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (480000, 500000)
  MAX_ITER: 540000
  CHECKPOINT_PERIOD: 120000
